import mysql.connector
from mysql.connector import Error

try:
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="mysql"  # ЁЯСЙ ржПржЦрж╛ржирзЗ ржпржжрж┐ рждрзЛржорж╛рж░ ржЕржирзНржп ржкрж╛рж╕ржУрзЯрж╛рж░рзНржб рж╣рзЯ, рж╕рзЗржЯрж╛ ржжрж╛ржУ
    )

    if mydb.is_connected():
        print("тЬЕ Connected to MySQL server")

        mycursor = mydb.cursor()

        db_name = "python_test_db"
        mycursor.execute(f"CREATE DATABASE {db_name}")
        print(f"ЁЯОЙ Database '{db_name}' created successfully!")

except Error as e:
    print("тЭМ Error:", e)
    

finally:
    if mydb.is_connected():
        mycursor.close()
        mydb.close()
        print("ЁЯФТ MySQL connection closed")
